<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MNK2190" failures="1" tests="5" name="TestCase.Test_dependency" time="0.022" errors="0" timestamp="2021-08-05T10:46:35 IST" skipped="2">
  <testcase classname="TestCase.Test_dependency" name="name3" time="0.012"/>
  <system-out/>
  <testcase classname="TestCase.Test_dependency" name="name5" time="0.004">
    <skipped/>
  </testcase> <!-- name5 -->
  <system-out/>
  <testcase classname="TestCase.Test_dependency" name="name2" time="0.000">
    <skipped/>
  </testcase> <!-- name2 -->
  <system-out/>
  <testcase classname="TestCase.Test_dependency" name="name1" time="0.003">
    <failure message="name-1 fail" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: name-1 fail
at org.testng.Assert.fail(Assert.java:99)
at TestCase.Test_dependency.name1(Test_dependency.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- name1 -->
  <system-out>
    <![CDATA[<a href="C:\Users\Administrator\Desktop\Wallpics\a.jpg" target="_blank">Failed element screenshot</a>
<br>
<a href="C:\Users\Administrator\Desktop\Wallpics\a.jpg" target="_blank"><img height=100 width=150 src="C:\Users\Administrator\Desktop\Wallpics\b.jpg"></a>]]>
  </system-out>
  <testcase classname="TestCase.Test_dependency" name="name4" time="0.003"/>
  <system-out/>
</testsuite> <!-- TestCase.Test_dependency -->
